import type { WebProject } from './types'

export const WEB_PROJECTS: readonly WebProject[] = [
  {
    slug: 'inatel2',
    title: 'Inatel²',
    summary: 'Em breve.',
    stack: ['Next.js', 'React', 'TypeScript'],
    repoUrl: 'https://github.com/XkrulesVitor/Inatel2',
    year: 2025,
    images: [],
    accent: '#3b82f6',
  },
  {
    slug: 'cp2ejr',
    title: 'CP2eJR - Corporative',
    summary: 'Em breve.',
    role: 'Gerente',
    stack: ['HTML', 'CSS', 'JavaScript'],
    repoUrl: 'https://github.com/NECP2eJr/Corporative-CP2eJr',
    year: 2025,
    images: [],
    accent: '#22c55e',
  },
  {
    slug: 'mrp-mobi',
    title: 'MRP Mobi',
    summary: 'Em breve.',
    stack: ['Next.js', 'React', 'TypeScript', 'Tailwind CSS'],
    repoUrl: 'https://github.com/XkrulesVitor/MRP-Mobi',
    liveUrl: 'https://mobi-lilac.vercel.app',
    year: 2026,
    images: [],
    accent: '#ff6b00',
  },
  {
    slug: 'memory-game',
    title: 'Jogo da Memória',
    summary: 'Em breve.',
    stack: ['Next.js', 'React', 'Tailwind CSS'],
    repoUrl: 'https://github.com/XkrulesVitor/Memory-Game-React',
    year: 2026,
    images: [],
    accent: '#a855f7',
  },
  {
    slug: 'love-letter',
    title: 'Carta de Amor Interativa',
    summary: 'Em breve.',
    stack: ['Next.js', 'TypeScript', 'Tailwind CSS'],
    repoUrl: 'https://github.com/XkrulesVitor/Template-for-Love-Letter',
    year: 2026,
    images: [],
    accent: '#f43f5e',
  },
  {
    slug: 'made-by-you',
    title: 'Made By You',
    summary: 'Em breve.',
    role: 'Contribuinte (Privado)',
    stack: ['React', 'TypeScript'],
    repoUrl: 'https://github.com/XkrulesVitor/Made-By-You',
    year: 2026,
    images: [],
    accent: '#ec4899',
  },
  {
    slug: 'noronha-app',
    title: 'Noronha App',
    summary: 'Em breve.',
    role: 'Privado',
    stack: ['React Native', 'TypeScript'],
    repoUrl: 'https://github.com/XkrulesVitor/Noronha-App',
    year: 2026,
    images: [],
    accent: '#06b6d4',
  },
  {
    slug: 'val-finance',
    title: 'V.A.L Finance',
    summary: 'Em breve.',
    role: 'Privado',
    stack: ['Next.js', 'TypeScript', 'Tailwind CSS'],
    repoUrl: 'https://github.com/XkrulesVitor/V.A.L-Finance',
    year: 2026,
    images: [],
    accent: '#10b981',
  },
  {
    slug: 'lp-jessica',
    title: 'LP Jessica',
    summary: 'Em breve.',
    role: 'Contribuinte',
    stack: ['HTML', 'CSS', 'JavaScript'],
    repoUrl: 'https://github.com/NECP2eJr/LP-Jessica',
    year: 2025,
    images: [],
    accent: '#f59e0b',
  },
  {
    slug: 'dicionario-c04a',
    title: 'Dicionário C04A',
    summary: 'Em breve.',
    role: 'Contribuinte',
    stack: ['React', 'TypeScript'],
    repoUrl: 'https://github.com/enzors444/dicionario-C04A',
    year: 2025,
    images: [],
    accent: '#6366f1',
  },
]
