import type { GameProject } from './types'

export const GAME_PROJECTS: readonly GameProject[] = [
  {
    slug: 'porrilandia',
    title: 'Porrilândia',
    kind: 'digital',
    context: 'Game Jam CrazyGames',
    year: 2026,
    summary: 'Em breve.',
    accent: '#e4572e',
    images: [],
    links: [
      { label: 'Itch.io', href: 'https://xkrulesf3lipe.itch.io/porriland', kind: 'itch' },
      { label: 'Repositório', href: 'https://github.com/XkrulesVitor/PorriLand', kind: 'repo' },
    ],
  },
  {
    slug: 'peter',
    title: 'As Aventuras de Peter',
    kind: 'digital',
    context: 'Game Jam CPG 2026',
    engine: 'GameMaker',
    year: 2026,
    summary: 'Em breve.',
    accent: '#4c8bf5',
    images: [],
    links: [
      { label: 'Itch.io', href: 'https://xkrulesf3lipe.itch.io/piter', kind: 'itch' },
      {
        label: 'Repositório',
        href: 'https://github.com/XkrulesVitor/PIter-Math-Adventure',
        kind: 'repo',
      },
    ],
  },
  {
    slug: 'o_anel',
    title: 'O Anel',
    kind: 'digital',
    context: 'Game Jam',
    summary: 'Em breve.',
    accent: '#f2c14e',
    images: [],
    links: [
      { label: 'Itch.io', href: 'https://xkrulesf3lipe.itch.io/um-jogo-de-hordas-o-anel', kind: 'itch' },
    ],
  },
  {
    slug: 'racco',
    title: 'Racco',
    kind: 'digital',
    context: 'Game Jam',
    summary: 'Em breve.',
    accent: '#10b981',
    images: [],
    links: [
      { label: 'Itch.io', href: 'https://beinez.itch.io/racco', kind: 'itch' },
    ],
  },
  {
    slug: 'memory_game',
    title: 'Jogo da Memória',
    kind: 'digital',
    summary: 'Em breve.',
    accent: '#a855f7',
    images: [],
    links: [
      { label: 'Repositório', href: 'https://github.com/XkrulesVitor/Memory-Game-React', kind: 'repo' },
    ],
  },
  {
    slug: 'terra',
    title: 'Expansão de Terra',
    kind: 'tabuleiro',
    context: 'Expansão',
    summary: 'Em breve.',
    accent: '#57b894',
    images: [],
    links: [],
  },
  {
    slug: 'aldeia_dorme',
    title: 'A Aldeia Dorme',
    kind: 'tabuleiro',
    summary: 'Em breve.',
    accent: '#3a3f8f',
    images: [],
    links: [],
  },
]
